### ISSUE TITLE
Heavy Bottleneck Preventing Updates

### ISSUE THREAD

**Issue by haxys** [TorSpider/TorSpider-Backend#15]
See [TorSpider issue 24](https://github.com/TorSpider/TorSpider/issues/24). With one or two nodes connected to the server, everything seems to run okay. Once you get about six nodes connected, the backend freezes up and starts giving 500-series errors.

**Comment by haxys** [comment]
I'm not sure what kind of changes might be made to the backend to improve the speed with which it can handle incoming requests. The backend will need to be able to handle a heavy load if we're going to have a multitude of remote nodes feeding it data. Any ideas how we can improve the speed of the backend?

**Comment by artagel** [comment]
The problem is the next_url query is quite expensive.
In the long run, the expense is because of probably not the best db schema.  Also, we should move to a queueing system instead of the query system for next url, because the spiders generally query that often.  When the query is expensive with joins, it creates a bottleneck, and we end up running out of queue pools in the application.

**Comment by haxys** [comment]
I've reduced the cost of the query by changing it as follows:

```python
candidates = Urls.query.join(Onions).filter(
        or_(
            and_(
                Urls.fault == None,
                Urls.date < week_ago
            ),and_(
                Onions.online == True,
                Onions.tries != 0,
                Onions.last_node != node_name
            ),and_(
                Onions.online == False,
                Onions.scan_date < day_ago,
                Onions.last_node != node_name
            )
        )
    ).order_by(
        db.func.random()
    ).limit(1).all()
```

If this code works as I expect it to, it will let the database handle selecting a single random url from the list, rather than pulling all onions and leaving that randomization up to the backend. This should make the query less costly.

**Comment by eloquentmess** [comment]
Unfortunately, try as I might, I've been unable to get the frontend and backend to function on my personal test server, so I haven't been able to verify this work. It's sitting in the `fix_next_url_query` backend branch.

**Comment by haxys** [comment]
The new query seems to work a bit better, but the servers still get overloaded pretty quick. I think it would help if the database pulled a block of URLs all at once and fed them out, only replenishing the block as necessary rather than running a full query every time a new url is needed.
