### ISSUE TITLE
Create non-live and live top20 lists

### ISSUE THREAD

**Issue by artagel** [TorSpider/TorSpider-Backend#17]
I believe the live top20 lists should be private.  
The non-live ones are generated periodically, perhaps every 30min-1hr, and are statically provided to the frontend, where the impact of web loads won't be detrimental for a simple query vs expensive top20 queries.

**Comment by haxys** [comment]
Agreed. There's no need for constantly-updated top-20 lists. They could be generated once every 24 hours.
